# -*- coding: utf-8 -*-
"""sample.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1htOL2YEYTVeBnGicViohxO5Z7ZlwKU8I
"""

import pandas as pd